let mySprite = Render.getRenderSpriteVariable()
tiles.placeOnTile(mySprite, tiles.getTileLocation(31, 62))
tiles.setCurrentTilemap(tilemap`level`)
let statusbar = statusbars.create(60, 4, StatusBarKind.Health)
statusbar.setLabel("HP")
statusbar.positionDirection(CollisionDirection.Top)
